# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления ответа')),
            ],
            options={
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('date_added',), 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='question',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления вопроса'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questApp.Question'),
        ),
    ]
